version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: expo
    versions:
    - 40.0.1
    - 41.0.0
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: socket.io
    versions:
    - 3.1.0
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: react-navigation
    versions:
    - 4.4.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: redux
    versions:
    - 4.0.5
